### ISSUE TITLE
Upstream proxy

### ISSUE THREAD

**Issue by traddy** [nccgroup/Berserko#3]
No option to select Kerberos as auth method when setting up Upstream proxy. 
Tried "None" with Kerberos enabled in Beresko - didn't work. 
Any hints on how to get this working? 
v1.7.22 Burp.

**Comment by rtt-ncc** [comment]
Hi

Do you mean that you have an upstream proxy which requires you to authenticate to it using Kerberos?
Unfortunately Berserko doesn't support this. It only supports authenticating directly to web servers.
Burp doesn't expose the upstream proxy authentication process through the extension API, so there's no way for Berserko to hook into this functionality.

Have you tried selecting NTLM as the upstream proxy authentication method? I would have thought that most proxies that supported Kerberos would also support NTLM (although I guess you probably have tried it which is why you were asking the question in the first place)

Richard

**Comment by traddy** [comment]
Hey! 
Yeah, we've tried NTLM without Beresko and it works okay, but since Beresko adds the Kerberos authentification functionality, we were hoping to auth against the upstream proxy via Burp with kerberos.

Thank you for your explanation though.
