### ISSUE TITLE
KDC: ICMP Port Unreachable

### ISSUE THREAD

**Issue by blshkv** [nccgroup/Berserko#8]
Hi, my target is an internal application and I had to setup SSH port forwarding of two ports: 443/tcp and 88/tcp.
The nmap is able to connect and verify users: ```nmap -p 88 --script=krb5-enum-users <skip>```

However, the plugin fails to "test domain settings" and fails to start eventually:
```
2020-12-21 12:09:00.282: Loaded config...
Domain DNS Name     : mybox.local
KDC Host            : 127.0.0.1
Username            : XXX
Password            : 
Save password       : false
Everything in scope : false
Domain in scope     : true
Hosts in scope      : app.mybox.local
Include plainhosts  : true
Ignore NTLM servers : false
Alert level         : 1
Logging level       : 1
Auth strategy       : PROACTIVE
Kerberos authentication disabled
Kerberos Authentication version 1.0
Kerberos authentication enabled
Unexpected error when testing connectivity to KDC: Connection refused (Connection refused)
Unexpected error when making test Kerberos request to KDC: ICMP Port Unreachable
```

I haven't check the source code, but is ICMP probe really mandatory? Can make it optional please?

**Comment by blshkv** [comment]
I got a hint from tcpdump while debugging the issue:
```12:49:55.356773 IP 127.0.0.1 > 127.0.0.1: ICMP 127.0.0.1 udp port 88 unreachable, length 198```
may be it can be disabled in krb5.conf ....

**Comment by blshkv** [comment]
ok, found a solution. I forced tcp connection by using the following krb5.conf config:
```
[libdefaults]
forwardable = true
udp_preference_limit = 1
```

**Comment by rtt-ncc** [comment]
Just reopening this to comment....

Thanks for raising this. I'll update the Berserko documentation to highlight that it's easy to get it to work over TCP rather than UDP in this way. Did use this recently when we were trying to get it to work in another port forwarding situation.

BTW Berserko doesn't make any ICMP requests, that error message above would have been an ICMP message from your local box due to the (UDP) port not being open.
